### ISSUE TITLE
Specify versions of source code repositories

### ISSUE THREAD

**Issue by pejalo** [vinniefalco/Amalgams#2]
After an unsuccessful attempt to update the TagLib template in this repository to create an amalgam of the latest release, I am trying to get this template working as-is with whatever version of TagLib was used at the time. Based on the timing and commit history of [TagLibAmalgam](https://github.com/vinniefalco/TagLibAmalgam) I would expect this to work with version [1.7.1](https://github.com/taglib/taglib/releases/tag/v1.7.1) or [1.7.2](https://github.com/taglib/taglib/releases/tag/v1.7.2). However this template references files not present in either version, e.g. `toolkit/tbytevectorstream.h`, `toolkit/tiostream.h`, `toolkit/tfilestream.h`. [1.8](https://github.com/taglib/taglib/releases/tag/v1.8) includes those files but the resulting amalgam will not compile because of other errors ("Redefinition of 'defaultStringHandler' with a different type").
